# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-15 18:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('springtime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('refNumber', models.IntegerField(max_length=8, primary_key=True, serialize=False)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('revNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateField(auto_now=True)),
                ('content', models.CharField(max_length=120)),
                ('rating', models.IntegerField(max_length=5)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trampoline',
            fields=[
                ('trampolineID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('broken', models.BooleanField()),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='trampolineID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='springtime.Trampoline'),
        ),
        migrations.AddField(
            model_name='booking',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
