# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-15 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springtime', '0002_auto_20170315_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='refNumber',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
