# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-15 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('springtime', '0003_auto_20170315_1836'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
