# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-16 02:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('springtime', '0004_auto_20170315_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='refNumber',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='trampolineID',
        ),
        migrations.AddField(
            model_name='booking',
            name='trampolineID',
            field=models.ManyToManyField(to='springtime.Trampoline'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='userID',
        ),
        migrations.AddField(
            model_name='booking',
            name='userID',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='revNumber',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='trampoline',
            name='trampolineID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
