# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-16 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springtime', '0005_auto_20170316_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trampoline',
            name='trampolineID',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
